# Generated by Django 5.2.8 on 2025-11-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-clics_carrito', '-fecha_registro']},
        ),
        migrations.AddField(
            model_name='producto',
            name='clics_carrito',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_vendedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
